# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

destinations = Destination.create([{name: 'Paris', weather: '18°C', description: 'París es la capital de Francia y su ciudad más poblada. Capital de la región de Isla de Francia, constituye el único departamento unicomunal del país. La ciudad de París, dentro de sus estrechos límites administrativos, tiene una población de 2 273 305 habitantes en 2015.​', timezone: 'GMT+1', cityimage: 'http://amicsliceu.com/wp-content/uploads/2018/12/paris_noche_museos_01-1.jpg', landingtime: '2019-07-02 08:00:00', boardingtime: '2019-07-02 10:00:00'},
    {name: 'Roma', weather: '20°C', description: 'Roma es una ciudad italiana de 2 857 321 habitantes, ​ capital de la región del Lacio y de Italia. Es el municipio más poblado de Italia y la cuarta ciudad más poblada de la Unión Europea.​', timezone: 'GMT+2', cityimage: 'https://www.hoteltexroma.it/sites/default/files/styles/photo_gallery/public/roma1.jpg?itok=AJVkQP5T', landingtime: '2019-07-03 09:00:00', boardingtime: '2019-07-03 22:30:00'},
    {name: 'Cataluña', weather: '22°C', description: 'Es una comunidad autónoma española, considerada nacionalidad histórica, situada en el nordeste de la península ibérica​.', timezone: 'GMT+1', cityimage: 'https://www.economiadigital.es/uploads/s1/63/20/80/7/barcelona-buildings-city-1388030_15_970x597.jpeg', landingtime: '2019-07-04 07:00:00', boardingtime: '2019-07-04 20:00:00'},
    {name: 'Atenas', weather: '17°C', description: 'Es la capital de Grecia y actualmente la ciudad más grande del país, su nombre posiblemente se deba en nombre de la diosa Atena.​', timezone: 'GMT+3', cityimage: 'https://cdn.civitatis.com/grecia/atenas/tour-privado-atenas.jpg', landingtime: '2019-07-05 08:00:00', boardingtime: '2019-07-05 22:00:00'},
    {name: 'Chipre', weather: '14°C', description: 'Es un Estado miembro de la Unión Europea situado en la isla homónima, cuya forma de gobierno es la república presidencialista. Su territorio está organizado en seis distritos administrativos. Su capital es Nicosia.​', timezone: 'GMT+3', cityimage: 'https://www.taranna.com/docs/viajes-a-chipre.jpg', landingtime: '2019-07-06 08:00:00', boardingtime: '2019-07-06 12:00:00'},
    {name: 'Albania', weather: '12°C', description: 'Es un país situado en el sureste de Europa. Limita con Montenegro al noroeste, con Kosovo al noreste, con Macedonia del Norte al este y con Grecia por el sur y el sureste. Tiene costa hacia el mar Adriático en el oeste y hacia el mar Jónico al suroeste.', timezone: 'GMT+2', cityimage: 'https://suitcasemag.com/wp-content/uploads/2018/05/albania-beach-umbrellas-1920x1081.jpg', landingtime: '2019-07-06 14:00:00', boardingtime: '2019-07-06 22:00:00'},
    {name: 'Lisboa', weather: '19°C', description: 'Lisboa es la capital​ y mayor ciudad de Portugal. Situada en la desembocadura del río Tajo, es la capital del país, capital del distrito de Lisboa, de la región de Lisboa, del Área Metropolitana de Lisboa, y es también el principal centro de la subregión de la Gran Lisboa.​', timezone: 'GMT+1', cityimage: 'https://www.lisboatours.es/images/buendia/guia-lisboa/informacion-practica-lisboa-top.jpg', landingtime: '2019-07-07 08:00:00', boardingtime: '2019-07-07 14:00:00'}])